### ISSUE TITLE
Метод в форме CustomFilterField getFromTo 

### ISSUE THREAD

**Issue by AlexandrGordeev** [studio107/CustomFields#1]
Метод в форме CustomFilterField getFromTo строит не верный запрос,  использовать агрегатные функции по полям связных таблиц нельзя.
 
Пример запроса с функцией max, который строиться:

SELECT MAX(`custom_fields_custom_value_float_3`.`value`) FROM `custom_catalog_product` `custom_catalog_product_1` INNER JOIN `custom_fields_custom_value_float` `custom_fields_custom_value_float_3` ON `custom_catalog_product_1`.id = custom_fields_custom_value_float_3.object_id WHERE (`custom_fields_custom_value_float_3`.`custom_field_id`='3') AND ((`custom_catalog_product_1`.`category_id`='5'))

Выдает несуществующие значения в таблице с алиасом custom_fields_custom_value_float_3

**Comment by AlexandrGordeev** [comment]
Вопрос снят

**Comment by max107** [comment]
@AlexandrGordeev а опишешь суть проблемы и пример кода?
